name: seabot
description: "SeaBot - Chat de apoyo emocional"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  provider: ^6.1.2
  flutter_pdfview: ^1.4.3
  photo_view: ^0.15.0
  webview_flutter: ^4.13.0
  youtube_player_flutter: ^9.1.3
  path_provider: ^2.1.5
  lottie: ^3.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/SeaBot.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/SeaBot.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/avatars/
    - assets/docs/
